"""Reusable ReportLab flowable components for PDF analytics reports.

All components use the design system from pdf_styles.py.
"""

import logging
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.platypus import (
    Flowable,
    Image,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.utils.pdf_styles import (
    ACCENT_AMBER,
    ACCENT_BAR_HEIGHT,
    ACCENT_BLUE,
    ACCENT_BLUE_LIGHT,
    ACCENT_GREEN,
    ACCENT_GREEN_LIGHT,
    ACCENT_RED,
    ACCENT_RED_LIGHT,
    BG_CARD,
    BORDER,
    BORDER_LIGHT,
    CARD_RADIUS,
    CONTENT_WIDTH,
    ICONS_DIR,
    MARGIN,
    PAGE_HEIGHT,
    PAGE_WIDTH,
    TEXT_MUTED,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    format_currency,
    get_styles,
    register_fonts,
)

logger = logging.getLogger(__name__)


# ── Page Callbacks (Header / Footer) ──────────────────────


def draw_branded_header(
    canvas: Any,
    doc: Any,
    subtitle: str = "Vehicle Analytics Report",
    *,
    app_name: str = "MyGarage",
    logo_path: str | None = None,
) -> None:
    """Draw the branded header on the first page only."""
    if doc.page > 1:
        return

    canvas.saveState()
    body, body_bold, mono, _ = register_fonts()

    x_left = MARGIN
    y_top = PAGE_HEIGHT - MARGIN

    # Brand icon (44x44) — custom logo or MG tile
    icon_size = 44
    icon_x = x_left
    icon_y = y_top - icon_size

    drew_logo = False
    if logo_path:
        try:
            canvas.drawImage(
                logo_path,
                icon_x,
                icon_y,
                width=icon_size,
                height=icon_size,
                preserveAspectRatio=True,
                mask="auto",
            )
            drew_logo = True
        except Exception:
            logger.warning("Failed to draw custom PDF logo from %s", logo_path, exc_info=True)

    if not drew_logo:
        canvas.setFillColor(ACCENT_BLUE)
        canvas.roundRect(icon_x, icon_y, icon_size, icon_size, 12, fill=1, stroke=0)

        # Initials from display name (fallback "MG")
        initials = "".join(part[0] for part in app_name.split() if part)[:2].upper() or "MG"
        canvas.setFillColor(colors.white)
        canvas.setFont(body_bold, 18)
        canvas.drawCentredString(icon_x + icon_size / 2, icon_y + 15, initials)

    # Brand text
    text_x = icon_x + icon_size + 14
    canvas.setFillColor(TEXT_PRIMARY)
    canvas.setFont(body_bold, 22)
    canvas.drawString(text_x, icon_y + icon_size - 20, app_name)

    canvas.setFillColor(TEXT_SECONDARY)
    canvas.setFont(body, 13)
    canvas.drawString(text_x, icon_y + icon_size - 38, subtitle)

    # Date/time (right-aligned)
    now = datetime.now()
    date_str = now.strftime("%B %d, %Y")
    time_str = now.strftime("%I:%M %p CST")

    x_right = PAGE_WIDTH - MARGIN
    canvas.setFillColor(TEXT_SECONDARY)
    canvas.setFont(mono, 13)
    canvas.drawRightString(x_right, icon_y + icon_size - 18, date_str)

    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont(mono, 12)
    canvas.drawRightString(x_right, icon_y + icon_size - 35, time_str)

    # Bottom border line
    line_y = icon_y - 12
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(2)
    canvas.line(x_left, line_y, x_right, line_y)

    canvas.restoreState()


def draw_branded_footer(
    canvas: Any,
    doc: Any,  # pyright: ignore[reportUnusedParameter]
    *,
    app_name: str = "MyGarage",
) -> None:
    """Draw the branded footer on every page."""
    canvas.saveState()
    body, body_bold, mono, _ = register_fonts()

    x_left = MARGIN
    x_right = PAGE_WIDTH - MARGIN
    y = MARGIN - 5

    # Top border line
    line_y = y + 25
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(2)
    canvas.line(x_left, line_y, x_right, line_y)

    # Left: "Generated by {app_name} · homelabforge.io"
    canvas.setFillColor(TEXT_MUTED)
    canvas.setFont(body, 12)
    canvas.drawString(x_left, y + 5, "Generated by ")

    text_w = canvas.stringWidth("Generated by ", body, 12)
    canvas.setFont(body_bold, 12)
    canvas.setFillColor(TEXT_SECONDARY)
    canvas.drawString(x_left + text_w, y + 5, app_name)

    bold_w = canvas.stringWidth(app_name, body_bold, 12)
    canvas.setFont(body, 12)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(x_left + text_w + bold_w, y + 5, " · homelabforge.io")

    # Right: version + report ID
    now = datetime.now()
    prefix = "".join(part[0] for part in app_name.split() if part)[:2].upper() or "MG"
    report_id = f"{prefix}-{now.strftime('%Y%m%d-%H%M%S')}"
    canvas.setFont(mono, 11)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawRightString(x_right, y + 5, f"v2.21 · {report_id}")

    canvas.restoreState()


# ── Section Header ─────────────────────────────────────────


def make_section_header(
    title: str,
    annotation: str | None = None,
    compact_title: bool = False,
) -> Table:
    """Create a section header with title and extending horizontal rule.

    Args:
        title: Section title text.
        annotation: Optional right-aligned annotation (e.g., "4 vendors").
        compact_title: Use smaller font to fit long titles on one line.
    """
    styles = get_styles()

    # Build row content
    if compact_title:
        from reportlab.lib.styles import ParagraphStyle

        compact_style = ParagraphStyle(
            "SectionTitleCompact",
            parent=styles["SectionTitle"],
            fontSize=13,
            leading=17,
        )
        title_para = Paragraph(title, compact_style)
    else:
        title_para = Paragraph(title, styles["SectionTitle"])

    # The line is implemented via table border styling
    if annotation:
        ann_para = Paragraph(annotation, styles["Annotation"])
        data = [[title_para, "", ann_para]]
        col_widths = [None, None, 1.5 * inch]
    else:
        data = [[title_para, ""]]
        col_widths = [None, None]

    t = Table(data, colWidths=col_widths)

    style_cmds: list[Any] = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        # Horizontal rule under the whole row
        ("LINEBELOW", (0, 0), (-1, 0), 1, BORDER_LIGHT),
    ]
    t.setStyle(TableStyle(style_cmds))
    return t


# ── Card Container ─────────────────────────────────────────


def wrap_in_card(flowable: Flowable | Table | list, padding: int = 24) -> Table:
    """Wrap a flowable or list of flowables in a card-style container.

    Creates a rounded rectangle with #f8f9fb background and #e2e5ec border.
    """
    if isinstance(flowable, list):
        content = flowable
    else:
        content = [flowable]

    # Use a single-cell table for the card
    inner_table = Table([[c] for c in content])
    inner_table.setStyle(
        TableStyle(
            [
                ("LEFTPADDING", (0, 0), (-1, -1), padding),
                ("RIGHTPADDING", (0, 0), (-1, -1), padding),
                ("TOPPADDING", (0, 0), (0, 0), padding),
                ("BOTTOMPADDING", (0, 0), (-1, -1), padding),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    card = Table([[inner_table]], colWidths=[CONTENT_WIDTH])
    card.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("ROUNDEDCORNERS", [CARD_RADIUS, CARD_RADIUS, CARD_RADIUS, CARD_RADIUS]),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return card


def style_as_card(table: Table, padding: int = 8) -> Table:
    """Apply card-style background and border directly to a Table.

    Unlike wrap_in_card, this keeps the Table splittable across pages
    because it doesn't nest inside a single-cell container. Use this
    for data tables that may have many rows (e.g., vehicle cost table).
    """
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("ROUNDEDCORNERS", [CARD_RADIUS, CARD_RADIUS, CARD_RADIUS, CARD_RADIUS]),
                ("LEFTPADDING", (0, 0), (-1, -1), padding),
                ("RIGHTPADDING", (0, 0), (-1, -1), padding),
            ]
        )
    )
    return table


# ── Vehicle Banner ─────────────────────────────────────────


def make_vehicle_banner(
    vehicle_name: str,
    vin: str,
    vehicle_type: str,
    days_owned: int | None = None,
) -> Table:
    """Create the vehicle banner card.

    Shows year/make/model in blue, VIN in monospace, and badges for type + tracking.
    """
    styles = get_styles()

    # Calculate months tracked
    months = days_owned // 30 if days_owned else 0
    tracking_text = f"{months} months tracked" if months > 0 else "New"

    # Vehicle info (left side)
    name_para = Paragraph(vehicle_name, styles["VehicleName"])
    vin_para = Paragraph(f"VIN {vin}", styles["VIN"])

    # Badges (right side)
    type_badge = _make_badge(vehicle_type, ACCENT_BLUE, ACCENT_BLUE_LIGHT)
    tracked_badge = _make_badge(tracking_text, ACCENT_GREEN, ACCENT_GREEN_LIGHT)

    badge_table = Table([[type_badge], [tracked_badge]])
    badge_table.setStyle(
        TableStyle(
            [
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )

    # Left column: name + VIN
    left_content = Table([[name_para], [vin_para]])
    left_content.setStyle(
        TableStyle(
            [
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )

    # Main layout
    banner_data = [[left_content, badge_table]]
    banner = Table(banner_data, colWidths=[CONTENT_WIDTH * 0.65, CONTENT_WIDTH * 0.35])
    banner.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("ROUNDEDCORNERS", [16, 16, 16, 16]),
                ("LEFTPADDING", (0, 0), (-1, -1), 32),
                ("RIGHTPADDING", (0, 0), (-1, -1), 32),
                ("TOPPADDING", (0, 0), (-1, -1), 28),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 28),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]
        )
    )
    return banner


# ── Garage Banner ──────────────────────────────────────────


def make_garage_banner(vehicle_count: int) -> Table:
    """Create the garage summary banner card."""
    styles = get_styles()

    heading = Paragraph("Total Vehicles:", styles["GarageHeading"])
    count_text = f"{vehicle_count} vehicle{'s' if vehicle_count != 1 else ''}"
    count_badge = _make_badge(count_text, ACCENT_BLUE, ACCENT_BLUE_LIGHT)

    banner_data = [[heading, count_badge]]
    banner = Table(banner_data, colWidths=[CONTENT_WIDTH * 0.7, CONTENT_WIDTH * 0.3])
    banner.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
                ("BOX", (0, 0), (-1, -1), 1, BORDER),
                ("ROUNDEDCORNERS", [16, 16, 16, 16]),
                ("LEFTPADDING", (0, 0), (-1, -1), 32),
                ("RIGHTPADDING", (0, 0), (-1, -1), 32),
                ("TOPPADDING", (0, 0), (-1, -1), 28),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 28),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]
        )
    )
    return banner


# ── Badge Helper ───────────────────────────────────────────


class _PillBadge(Flowable):
    """Pill-shaped badge drawn directly on canvas — no Table line artifacts."""

    _h_pad = 14
    _v_pad = 6

    def __init__(self, text: str, text_color: Any, bg_color: Any) -> None:
        super().__init__()
        styles = get_styles()
        self._text = text
        self._text_color = text_color
        self._bg_color = bg_color
        self._style = styles["Badge"]
        # Measure text to set flowable dimensions
        from reportlab.pdfbase.pdfmetrics import stringWidth

        self._text_w = stringWidth(text, self._style.fontName, self._style.fontSize)
        self.width = self._text_w + 2 * self._h_pad
        self.height = self._style.fontSize + 2 * self._v_pad

    def wrap(self, aW: float, aH: float) -> tuple[float, float]:  # noqa: ARG002, N803
        return (self.width, self.height)

    def draw(self) -> None:
        c = self.canv
        r = self.height / 2  # fully rounded ends
        # Background pill
        c.setFillColor(self._bg_color)
        c.setStrokeColor(self._bg_color)
        c.roundRect(0, 0, self.width, self.height, r, fill=1, stroke=0)
        # Text centered
        c.setFillColor(self._text_color)
        c.setFont(self._style.fontName, self._style.fontSize)
        c.drawCentredString(
            self.width / 2,
            self._v_pad,
            self._text,
        )


def _make_badge(text: str, text_color: Any, bg_color: Any) -> _PillBadge:
    """Create a small pill badge."""
    return _PillBadge(text, text_color, bg_color)


# ── KPI Card Row ───────────────────────────────────────────

# Accent color mapping
KPI_COLORS = {
    "blue": (ACCENT_BLUE, "#2563eb"),
    "green": (ACCENT_GREEN, "#059669"),
    "amber": (ACCENT_AMBER, "#d97706"),
    "red": (ACCENT_RED, "#dc2626"),
}


def make_kpi_row(
    cards: list[dict[str, Any]],
) -> Table:
    """Create a row of KPI cards (1-4 cards; 4 is the common case).

    Each card dict should have:
        label: str (uppercase label)
        value: str (formatted value)
        sub: str (sub-detail text)
        color: str ("blue", "green", "amber", "red")
        sub_html: str | None (optional HTML for sub-detail with colored badge)

    Card width divides the content width evenly by the number of cards
    passed (e.g. a 2-card hours-only summary gets half-width cards, not
    quarter-width cards floating in an otherwise-empty row).
    """
    styles = get_styles()
    num_cards = len(cards)
    card_width = CONTENT_WIDTH / num_cards

    cells = []
    for card in cards:
        accent_color, _ = KPI_COLORS.get(card["color"], KPI_COLORS["blue"])

        # Build card content as stacked paragraphs
        label_text = card["label"].upper()
        label = Paragraph(label_text, styles["KPILabel"])

        # Value with accent color
        value_style = styles["KPIValue"].__class__(
            f"KPIValue_{card['color']}",
            parent=styles["KPIValue"],
            textColor=accent_color,
        )
        value = Paragraph(card["value"], value_style)

        # Sub-detail
        sub_text = card.get("sub_html", card.get("sub", ""))
        sub = Paragraph(sub_text, styles["KPISub"])

        # Stack vertically
        cell_content = Table(
            [[label], [value], [sub]],
            colWidths=[card_width - 20],
        )
        cell_content.setStyle(
            TableStyle(
                [
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (0, 0), 6),  # Space after label
                    ("BOTTOMPADDING", (0, 1), (0, 1), 4),  # Space after value
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        cells.append(cell_content)

    # Create the KPI grid (evenly divided by however many cards were passed)
    kpi_table = Table([cells], colWidths=[card_width] * num_cards)

    style_cmds: list[Any] = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 18),  # Extra top padding for accent bar
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
    ]

    # Individual card styling (background, border, accent bar)
    for i, card in enumerate(cards):
        accent_color, _ = KPI_COLORS.get(card["color"], KPI_COLORS["blue"])
        style_cmds.extend(
            [
                ("BACKGROUND", (i, 0), (i, 0), BG_CARD),
                ("BOX", (i, 0), (i, 0), 1, BORDER),
                # Accent bar at top
                ("LINEABOVE", (i, 0), (i, 0), ACCENT_BAR_HEIGHT, accent_color),
            ]
        )

    # Add gaps between cards using inner grid
    style_cmds.append(("ROUNDEDCORNERS", [CARD_RADIUS, CARD_RADIUS, CARD_RADIUS, CARD_RADIUS]))

    kpi_table.setStyle(TableStyle(style_cmds))
    return kpi_table


# ── Vendor Card List ───────────────────────────────────────


def make_vendor_list(
    vendors: list[dict[str, Any]],
    most_used: str | None = None,
    highest_spend: str | None = None,
    currency_code: str = "USD",
    locale: str = "en-US",
) -> list:
    """Create a list of vendor cards.

    Returns a list of flowables (one Table per vendor).
    """
    styles = get_styles()
    flowables = []

    for i, vendor in enumerate(vendors):
        name = vendor.get("vendor_name", "Unknown")
        total = format_currency(vendor.get("total_spent", 0), currency_code, locale)
        count = vendor.get("service_count", 0)

        # Build detail text
        details = []
        details.append(f"{count} service{'s' if count != 1 else ''}")
        if name == highest_spend:
            details.append("Highest spend")
        elif name == most_used:
            details.append("Most used")

        detail_text = " · ".join(details)

        # Left side: name + detail
        name_para = Paragraph(name, styles["VendorName"])
        detail_para = Paragraph(detail_text, styles["VendorDetail"])
        left = Table([[name_para], [detail_para]])
        left.setStyle(
            TableStyle(
                [
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ]
            )
        )

        # Right side: amount
        amount_para = Paragraph(total, styles["VendorAmount"])

        row = Table(
            [[left, amount_para]],
            colWidths=[CONTENT_WIDTH * 0.7, CONTENT_WIDTH * 0.3],
        )

        style_cmds: list[Any] = [
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 18),
            ("RIGHTPADDING", (0, 0), (-1, -1), 18),
            ("TOPPADDING", (0, 0), (-1, -1), 14),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
            ("BACKGROUND", (0, 0), (-1, -1), BG_CARD),
            ("BOX", (0, 0), (-1, -1), 1, BORDER),
            ("ROUNDEDCORNERS", [10, 10, 10, 10]),
        ]

        # First vendor (top spender) gets blue accent
        if i == 0:
            style_cmds.extend(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), ACCENT_BLUE_LIGHT),
                    ("LINEBEFORE", (0, 0), (0, -1), 3, ACCENT_BLUE),
                ]
            )

        row.setStyle(TableStyle(style_cmds))
        flowables.append(row)
        flowables.append(Spacer(1, 10))

    return flowables


# ── Season Card Row ────────────────────────────────────────

SEASON_ICONS = {
    "Winter": "winter.png",
    "Spring": "spring.png",
    "Summer": "summer.png",
    "Fall": "fall.png",
}


def make_season_row(
    seasons: list[dict[str, Any]],
    highest_season: str | None = None,
    lowest_season: str | None = None,
    currency_code: str = "USD",
    locale: str = "en-US",
) -> Table:
    """Create a 4-column grid of seasonal spending cards."""
    styles = get_styles()

    cells = []
    for season in seasons:
        name = season.get("season", "")
        total = format_currency(season.get("total_cost", 0), currency_code, locale)
        count = season.get("service_count", 0)
        variance = float(str(season.get("variance_from_annual", 0)))

        # Build cell content
        cell_items = []

        # Season icon
        icon_file = ICONS_DIR / SEASON_ICONS.get(name, "")
        if icon_file.exists():
            cell_items.append(Image(str(icon_file), width=24, height=24))
            cell_items.append(Spacer(1, 4))

        # Season name
        cell_items.append(Paragraph(name, styles["SeasonName"]))
        cell_items.append(Spacer(1, 6))

        # Amount
        cell_items.append(Paragraph(total, styles["SeasonAmount"]))

        # Service count
        cell_items.append(
            Paragraph(f"{count} service{'s' if count != 1 else ''}", styles["SeasonServices"])
        )

        # Variance
        if variance > 0:
            var_text = f'<font color="#dc2626">+{variance:.1f}%</font>'
        elif variance < 0:
            var_text = f'<font color="#059669">{variance:.1f}%</font>'
        else:
            var_text = '<font color="#8c91a3">0.0%</font>'

        from reportlab.lib.styles import ParagraphStyle

        var_style = ParagraphStyle(
            "SeasonVariance",
            parent=styles["SeasonServices"],
            fontSize=11,
            alignment=TA_CENTER,
        )
        cell_items.append(Spacer(1, 4))
        cell_items.append(Paragraph(var_text, var_style))

        # Stack items vertically
        inner = Table([[item] for item in cell_items])
        inner.setStyle(
            TableStyle(
                [
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        cells.append(inner)

    # Wrap each cell in its own rounded card Table
    gap = 8
    card_width = (CONTENT_WIDTH - gap * (len(cells) - 1)) / max(len(cells), 1)

    card_cells = []
    for i, (cell_content, season) in enumerate(zip(cells, seasons)):
        name = season.get("season", "")

        bg = BG_CARD
        border_color = BORDER
        border_width = 1
        if name == highest_season:
            bg = ACCENT_RED_LIGHT
            border_color = ACCENT_RED
            border_width = 2
        elif name == lowest_season:
            bg = ACCENT_GREEN_LIGHT
            border_color = ACCENT_GREEN
            border_width = 2

        card = Table([[cell_content]], colWidths=[card_width])
        card.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), bg),
                    ("BOX", (0, 0), (-1, -1), border_width, border_color),
                    ("ROUNDEDCORNERS", [12, 12, 12, 12]),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 12),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                    ("TOPPADDING", (0, 0), (-1, -1), 16),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
                ]
            )
        )
        card_cells.append(card)

    # Outer grid just provides spacing — no borders
    col_widths_with_gaps = []
    for i in range(len(card_cells)):
        col_widths_with_gaps.append(card_width)
        if i < len(card_cells) - 1:
            col_widths_with_gaps.append(gap)

    # Interleave cards with spacer cells
    row_with_gaps: list[Any] = []
    for i, card in enumerate(card_cells):
        row_with_gaps.append(card)
        if i < len(card_cells) - 1:
            row_with_gaps.append("")  # gap cell

    grid = Table([row_with_gaps], colWidths=col_widths_with_gaps)
    grid.setStyle(
        TableStyle(
            [
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    return grid


# ── Data Table Helper ──────────────────────────────────────


def make_data_table(
    headers: list[str],
    rows: list[list[str | Paragraph]],
    col_widths: list[float] | None = None,
    highlight_row: int | None = None,
    amount_columns: list[int] | None = None,
    compact: bool = False,
) -> Table:
    """Create a styled data table matching the design system.

    Args:
        headers: Column header strings.
        rows: List of row data (strings or Paragraphs).
        col_widths: Optional column widths.
        highlight_row: Optional 0-based row index to highlight in blue.
        amount_columns: Optional list of column indices that contain monetary amounts.
        compact: If True, use smaller fonts and tighter padding for dense tables.
    """
    styles = get_styles()

    # Build header row
    header_style = styles["TableHeaderCompact"] if compact else styles["TableHeader"]
    header_paras = [Paragraph(h.upper(), header_style) for h in headers]
    table_data = [header_paras] + rows

    t = Table(table_data, colWidths=col_widths)

    if compact:
        pad = 4
        style_cmds: list[Any] = [
            # Header
            ("FONTNAME", (0, 0), (-1, 0), register_fonts()[1]),
            ("FONTSIZE", (0, 0), (-1, 0), 7),
            ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_MUTED),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
            ("TOPPADDING", (0, 0), (-1, 0), 6),
            ("LINEBELOW", (0, 0), (-1, 0), 2, BORDER),
            # Data rows
            ("FONTSIZE", (0, 1), (-1, -1), 9),
            ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_SECONDARY),
            ("TOPPADDING", (0, 1), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
            ("LINEBELOW", (0, 1), (-1, -2), 1, BORDER_LIGHT),
            # General
            ("LEFTPADDING", (0, 0), (-1, -1), pad),
            ("RIGHTPADDING", (0, 0), (-1, -1), pad),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    else:
        style_cmds = [
            # Header
            ("FONTNAME", (0, 0), (-1, 0), register_fonts()[1]),  # Bold
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_MUTED),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ("TOPPADDING", (0, 0), (-1, 0), 10),
            ("LINEBELOW", (0, 0), (-1, 0), 2, BORDER),
            # Data rows
            ("FONTSIZE", (0, 1), (-1, -1), 13),
            ("TEXTCOLOR", (0, 1), (-1, -1), TEXT_SECONDARY),
            ("TOPPADDING", (0, 1), (-1, -1), 11),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 11),
            ("LINEBELOW", (0, 1), (-1, -2), 1, BORDER_LIGHT),
            # General
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("RIGHTPADDING", (0, 0), (-1, -1), 14),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

    # Right-align amount columns
    if amount_columns:
        for col in amount_columns:
            style_cmds.append(("ALIGN", (col, 0), (col, -1), "RIGHT"))

    # Highlight row
    if highlight_row is not None:
        row_idx = highlight_row + 1  # +1 for header
        style_cmds.append(("TEXTCOLOR", (0, row_idx), (0, row_idx), ACCENT_BLUE))

    t.setStyle(TableStyle(style_cmds))
    return t
